-- =========================================================
-- TIPOS CONTROLADOS
-- =========================================================

create type public.status_competencia as enum (
  'ABERTA',
  'EM_CONFERENCIA',
  'REABERTA',
  'FINALIZADA'
);

create type public.status_lancamento as enum (
  'ATIVO',
  'CANCELADO'
);

create type public.tipo_lancamento as enum (
  'FATURAMENTO',
  'DEVOLUCAO_ESTORNO'
);

-- =========================================================
-- EMPRESAS
-- =========================================================

create table public.empresas (
  id bigint generated by default as identity primary key,
  razao_social varchar(200) not null,
  nome_fantasia varchar(150),
  cnpj varchar(14) not null unique,
  ativa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint empresas_cnpj_formato_check
    check (cnpj ~ '^[0-9]{14}$')
);

-- =========================================================
-- USUARIOS
-- =========================================================

create table public.usuarios (
  id uuid primary key
    references auth.users(id)
    on delete restrict,

  nome varchar(150) not null,
  email varchar(255) not null unique,
  cargo varchar(50) not null,
  ativo boolean not null default true,
  ultimo_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================================================
-- CATEGORIAS DE FATURAMENTO
-- =========================================================

create table public.categorias_faturamento (
  id bigint generated by default as identity primary key,
  nome varchar(120) not null unique,
  descricao text,
  ativa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =========================================================
-- COMPETENCIAS
-- =========================================================

create table public.competencias (
  id bigint generated by default as identity primary key,

  empresa_id bigint not null
    references public.empresas(id)
    on delete restrict,

  ano integer not null,
  mes integer not null,

  status public.status_competencia not null default 'ABERTA',

  sem_movimento boolean not null default false,
  sem_movimento_em timestamptz,

  sem_movimento_por uuid
    references public.usuarios(id)
    on delete restrict,

  conferencia_iniciada_em timestamptz,

  conferencia_iniciada_por uuid
    references public.usuarios(id)
    on delete restrict,

  finalizada_em timestamptz,

  finalizada_por uuid
    references public.usuarios(id)
    on delete restrict,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint competencias_empresa_ano_mes_unique
    unique (empresa_id, ano, mes),

  constraint competencias_mes_check
    check (mes between 1 and 12),

  constraint competencias_sem_movimento_check
    check (
      (
        sem_movimento = false
        and sem_movimento_em is null
        and sem_movimento_por is null
      )
      or
      (
        sem_movimento = true
        and sem_movimento_em is not null
        and sem_movimento_por is not null
      )
    )
);

-- =========================================================
-- HISTORICO DAS COMPETENCIAS
-- =========================================================

create table public.historico_competencias (
  id bigint generated by default as identity primary key,

  competencia_id bigint not null
    references public.competencias(id)
    on delete restrict,

  usuario_id uuid not null
    references public.usuarios(id)
    on delete restrict,

  status_anterior public.status_competencia not null,
  status_novo public.status_competencia not null,
  justificativa text,
  created_at timestamptz not null default now(),

  constraint historico_status_diferentes_check
    check (status_anterior <> status_novo),

  constraint historico_reabertura_justificada_check
    check (
      status_anterior <> 'EM_CONFERENCIA'
      or status_novo <> 'REABERTA'
      or nullif(btrim(justificativa), '') is not null
    )
);

-- =========================================================
-- LANCAMENTOS DE FATURAMENTO
-- =========================================================

create table public.lancamentos_faturamento (
  id bigint generated by default as identity primary key,

  competencia_id bigint not null
    references public.competencias(id)
    on delete restrict,

  categoria_id bigint not null
    references public.categorias_faturamento(id)
    on delete restrict,

  criado_por_usuario_id uuid not null
    references public.usuarios(id)
    on delete restrict,

  tipo_lancamento public.tipo_lancamento not null,
  data_referencia date not null,
  valor numeric(14, 2) not null,
  observacao text,

  status public.status_lancamento not null default 'ATIVO',

  cancelado_por_usuario_id uuid
    references public.usuarios(id)
    on delete restrict,

  cancelado_em timestamptz,
  motivo_cancelamento text,

  substitui_lancamento_id bigint unique
    references public.lancamentos_faturamento(id)
    on delete restrict,

  created_at timestamptz not null default now(),

  constraint lancamentos_valor_positivo_check
    check (valor > 0),

  constraint lancamentos_nao_substitui_proprio_check
    check (
      substitui_lancamento_id is null
      or substitui_lancamento_id <> id
    ),

  constraint lancamentos_cancelamento_coerente_check
    check (
      (
        status = 'ATIVO'
        and cancelado_por_usuario_id is null
        and cancelado_em is null
        and motivo_cancelamento is null
      )
      or
      (
        status = 'CANCELADO'
        and cancelado_por_usuario_id is not null
        and cancelado_em is not null
        and nullif(btrim(motivo_cancelamento), '') is not null
      )
    )
);

-- =========================================================
-- INDICES
-- =========================================================

create index competencias_empresa_id_idx
  on public.competencias (empresa_id);

create index historico_competencias_competencia_id_idx
  on public.historico_competencias (competencia_id);

create index historico_competencias_usuario_id_idx
  on public.historico_competencias (usuario_id);

create index lancamentos_competencia_id_idx
  on public.lancamentos_faturamento (competencia_id);

create index lancamentos_categoria_id_idx
  on public.lancamentos_faturamento (categoria_id);

create index lancamentos_criado_por_idx
  on public.lancamentos_faturamento (criado_por_usuario_id);

create index lancamentos_data_referencia_idx
  on public.lancamentos_faturamento (data_referencia);

-- =========================================================
-- ATUALIZACAO AUTOMATICA DE updated_at
-- =========================================================

create or replace function public.atualizar_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger empresas_atualizar_updated_at
before update on public.empresas
for each row
execute function public.atualizar_updated_at();

create trigger usuarios_atualizar_updated_at
before update on public.usuarios
for each row
execute function public.atualizar_updated_at();

create trigger categorias_atualizar_updated_at
before update on public.categorias_faturamento
for each row
execute function public.atualizar_updated_at();

create trigger competencias_atualizar_updated_at
before update on public.competencias
for each row
execute function public.atualizar_updated_at();

-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

alter table public.empresas enable row level security;
alter table public.usuarios enable row level security;
alter table public.categorias_faturamento enable row level security;
alter table public.competencias enable row level security;
alter table public.historico_competencias enable row level security;
alter table public.lancamentos_faturamento enable row level security;

-- O frontend não recebe acesso direto nesta primeira etapa.

revoke all on table public.empresas
  from anon, authenticated;

revoke all on table public.usuarios
  from anon, authenticated;

revoke all on table public.categorias_faturamento
  from anon, authenticated;

revoke all on table public.competencias
  from anon, authenticated;

revoke all on table public.historico_competencias
  from anon, authenticated;

revoke all on table public.lancamentos_faturamento
  from anon, authenticated;

-- A chave secreta utilizada pelo backend opera como service_role.

grant usage on schema public to service_role;

grant select, insert, update, delete
  on table
    public.empresas,
    public.usuarios,
    public.categorias_faturamento,
    public.competencias,
    public.historico_competencias,
    public.lancamentos_faturamento
  to service_role;

grant usage, select
  on all sequences in schema public
  to service_role;

revoke execute
  on function public.atualizar_updated_at()
  from public, anon, authenticated;
